[build]
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "PUBLIC_GISCUS_REPO,PUBLIC_GISCUS_REPO_ID,PUBLIC_GISCUS_CATEGORY,PUBLIC_GISCUS_CATEGORY_ID" }

[build.environment]
  NODE_VERSION = "22" 