[build]
  command = "npm run build && node scripts/netlify-screenshot-build.js"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
   SECRETS_SCAN_OMIT_KEYS = "PUBLIC_GISCUS_REPO,PUBLIC_GISCUS_REPO_ID,PUBLIC_GISCUS_CATEGORY,PUBLIC_GISCUS_CATEGORY_ID,SCREENSHOT_MACHINE_API_KEY"